pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = "zero-ide"

include "editor-api"
include "editor-core"
include "plugins:word-count-plugin"
include "plugins:markdown-tools-plugin"
include "plugins:java-snippets-plugin"
include "plugins:file-tree-plugin"
include "plugins:search-plugin"
include "plugins:git-plugin"
include "plugins:terminal-plugin"
include "plugins:markdown-preview-plugin"
include "vscode-compat"
