plugins {
    id "application"
    id "org.openjfx.javafxplugin" version "0.1.0"
}

dependencies {
    implementation project(":editor-api")
    implementation "com.fasterxml.jackson.core:jackson-databind:2.17.2"
    implementation "org.fxmisc.richtext:richtextfx:0.11.7"
    implementation "org.slf4j:slf4j-api:2.0.13"
    runtimeOnly "ch.qos.logback:logback-classic:1.5.6"
    implementation "org.springframework:spring-context:6.1.10"
}

javafx {
    version = "21.0.4"
    modules = ["javafx.controls"]
}

application {
    mainClass = "com.zeroide.core.ZeroIdeApp"
}

def zeroIdeJvmArgs = ["--enable-native-access=javafx.graphics"]
if (JavaVersion.current().majorVersion.toInteger() >= 24) {
    zeroIdeJvmArgs.add("--sun-misc-unsafe-memory-access=allow")
}

tasks.named("run") {
    dependsOn rootProject.tasks.named("copyRuntimePlugins")
    systemProperty "zeroide.pluginDir", rootProject.layout.buildDirectory.dir("runtime/plugins").get().asFile.absolutePath
    jvmArgs zeroIdeJvmArgs
}
